services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db

  app:
    image: ghcr.io/${GITHUB_REPOSITORY}:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped

volumes:
  mongo_data:
